<a href="https://colab.research.google.com/github/gandhias-a11y/colab/blob/main/midterm_lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1: (tested with the usfca visualization) Steps 1-6 are correct. Estimated score: 100%

Q2A: (tested with the usfca visualization) All inserts are correct

Q2B and Q2C: I believe them to be right based off my score from the first midterm.

Q2D: (tested with the usfca visualization) insertion and deletion are correctly shown.

total estimated score: 100%

Q3: Based off comparison to the diagram in the What's New seection of the class website, I believe that all of the diagrams are correct.
Estimated score: 100%

Q4: I believe the definitions are all accurate.
Estimated score: 100%

In [1]:
class Every():
 def one(self): return type(self).__name__ + self.two();
 def two(self): return "thing"
class Some(Every):
 def two(self): return "where"
class Any(Some):
 pass
a = Some()
print(a.one()) # 1.
b = Every()
print(b.one()) # 2.
c = Any()
print(c.one()) # 3.

Somewhere
Everything
Anywhere


Q5: All print statements are correct. Estimated score: 100%

In [ ]:
import re
s = "Let's eat, Grandma!"
p06 = re.sub(r'([^aeiouAEIOU])([^aeiouAEIOU])', lambda m: m.group(2) + m.group(1),s)
print(p06)

Le't sea,tG radnma!


Q6: The outputs are identical.
Estimated score: 100%

In [ ]:
import numpy as np
a = np.array([4, 2, 6, 5, 3, 8, 1, 7])
print(a[-2:3:-1])

b= a.reshape(2,4)
print(b[0:2, 1:3])

c= a.reshape(2,2,2)
print(c[0,:,:])

print(c[:,1,:].T)

print(c[:,:,1])

[1 8 3]
[[2 6]
 [8 1]]
[[4 2]
 [6 5]]
[[6 1]
 [5 7]]
[[2 5]
 [8 7]]


Q7: 1st print statement: correct
2nd print statement:correct
3rd print statement: correct
4th print statement: correct
5th print statement: 1/4 incorrect
estimated score: 90%

In [3]:
class LinkedList:
  def _init_(self, num, next):
    self.num = Num
    self.next = next
  def insert(self, value):
    if self.next is None:
      self.num = LinkedList(value, None)
    else:
      self.next.insert(value)
  def show(self):
    temp =self
    result = ""
    while (temp):
      result = result + " " + temp.num + " "
      temp = temp.next
    print(result)

Q8: Code runs correctly. Estimated score: 100